# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b65279fe3a3cde0d46c91443063fccb6a6bc332a41da3614ccc8a0c9761e04b83d39b52bba3997a7861764f5f34af2d949793a4979550483e1db1d8fd399c74

test:
  secret_key_base: 0c7c1a7506ce11ec61615a0b329930293619f0933a30ae8813a5e28491e162f594723d8a15daceba557b23fa958cde54785414ffe21c7ca21c45482c3458a360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
